### ISSUE TITLE
Determine supported parameters

### ISSUE THREAD

**Issue by blegat** [jump-dev/Cbc.jl#125]
See https://github.com/JuliaOpt/Cbc.jl/blob/e10628f91b7b357c48dbf92e1447df5feca598e9/src/MOI_wrapper.jl#L34-L38

**Comment by Wedg** [comment]
When I try to find the list of parameters by running the cbc executable (which I find inside deps\usr\bin) I get the following "`cbc.exe - System Error`":
"`The code execution cannot proceed because libgcc_s_seh-1.dll was not found. Reinstalling the program may fix this problem.`"
And this repeats for `libgfortran-3.dll` and `libstdc++-6.dll`
![cbc](https://user-images.githubusercontent.com/8735697/69495598-6c879500-0ed1-11ea-8f24-f0e63243af9c.PNG)

The solver does work withing JuMP. So it may not be a problem with the installation. But any idea why that does happen? And any suggestions for getting the list of parameters? Thank you!

**Comment by odow** [comment]
See https://projects.coin-or.org/CoinBinary/export/1059/OptimizationSuite/trunk/Installer/files/doc/cbcCommandLine.pdf

**Comment by lausilvag** [comment]
Hi
I am trying to set parameters for Cbc Solver

Z_OP = Model(with_optimizer(Cbc.Optimizer))
    set_parameter(Z_OP, "preProcess", off)
    set_parameter(Z_OP, "CliqueCuts", Root)
error:
UndefVarError: Off not defined
UndefVarError: Root not defined

Does anyone know how to fix the error and where can I find updated information on the command lines?

Thank you

**Comment by odow** [comment]
You need:
```Julia
set_parameter("Z_OP", "preProcess", "off")
set_parameter("Z_OP", "CliqueCuts", "Root")
```

**Comment by odow** [comment]
Closing because this doesn't seem like it will happen anytime soon. The README now documents how to use `Cbc_jll` to view the list of supported parameters.
