### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/Cbc.jl#208]
From the C interface, columns in Cbc seem to have variable names, not sure they can be set after creation though.
In any case, when the problem is created with copy_to, names could be passed as well

**Comment by odow** [comment]
Is there a need for this? I think I punted because we always use Cbc with a cache, and that stores the names. Supporting names is really only needed for solvers in direct-mode.

Methods are here:

https://github.com/jump-dev/Cbc.jl/blob/e028e26982d9b0b148e4e8e058d86be2333a65fb/src/gen/libcbc_api.jl#L41-L47

https://github.com/jump-dev/Cbc.jl/blob/e028e26982d9b0b148e4e8e058d86be2333a65fb/src/gen/libcbc_api.jl#L117-L123

**Comment by matbesancon** [comment]
the use case is solving instances loaded from a file with Cbc, it would be useful to have access to the names (and have them set at copy_to time)
